jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build --build-arg "APP_VERSION=${TRAVIS_COMMIT}" -t "eponae/cv:${TRAVIS_COMMIT}" .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u "eponae" --password-stdin
    - docker push "eponae/cv:${TRAVIS_COMMIT}"

  - stage: Publish

    sudo: required
    services:
    - docker
    script:
    - echo "${DOCKER_PASS}" | docker login -u "eponae" --password-stdin
    - docker pull "eponae/cv:${TRAVIS_COMMIT}"
    - docker tag "eponae/cv:${TRAVIS_COMMIT}" eponae/cv:latest
    - docker push eponae/cv:latest

  - stage: Deploy

    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: bash script/deploy eponae-cv "${TRAVIS_COMMIT}" "@docker-compose.yml"

stages:
  - Build
  - name: Publish
    if: branch = master
  - name: Deploy
    if: branch = master

notifications:
  email: false
