language: node_js
sudo: required
services:
- docker
node_js: 7
script: |
  npm run build

  DOCKER_IMAGE_DEFAULT=${DOCKER_USER}/cv
  DOCKER_IMAGE_NAME=${DOCKER_IMAGE_DEFAULT}
  if [ "${TRAVIS_BRANCH}" != "master" ]; then
    DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
  fi

  docker build -t ${DOCKER_IMAGE_NAME} .
after_success: |
  docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && docker push ${DOCKER_IMAGE_NAME}
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: 'curl -u "${DEPLOY_CREDENTIALS}" -X POST https://deploy.vibioh.fr/eponae-cv/${GIT_COMMIT} --data-binary @docker-compose.yml'
  on:
    all_branches: true
    condition: ${TRAVIS_BRANCH} == 'master'
- provider: script
  skip_cleanup: true
  script: >-
    cat docker-compose.yml | sed "s|traefik.frontend.rule.*|traefik.frontend.rule: 'Host: www-${TRAVIS_BRANCH}.eponae.fr'|" | sed "s|${DOCKER_IMAGE_DEFAULT}|${DOCKER_IMAGE_NAME}|" | curl -u '${DEPLOY_CREDENTIALS}' -X POST https://deploy.vibioh.fr/eponae-cv-${TRAVIS_BRANCH}/${TRAVIS_COMMIT} --data-binary @-
  on:
    all_branches: true
    condition: ${TRAVIS_BRANCH} != 'master'
