---

version: '2'

services:
  site:
    image: eponae/cv
    labels:
      traefik.http.routers.eponae-cv-http.rule: Host(`eponae.fr`) || Host(`www.eponae.fr`)
      traefik.http.routers.eponae-cv-http.entrypoints: http
      traefik.http.routers.eponae-cv-http.middlewares: redirect@file
      traefik.http.middlewares.eponae-wwwredirect.redirectregex.regex: ^https://eponae.fr(.*)
      traefik.http.middlewares.eponae-wwwredirect.redirectregex.replacement: https://www.eponae.fr$${1}
      traefik.http.middlewares.eponae-wwwredirect.redirectregex.permanent: true
      traefik.http.routers.eponae-cv-https.rule: Host(`eponae.fr`) || Host(`www.eponae.fr`)
      traefik.http.routers.eponae-cv-https.entrypoints: https
      traefik.http.routers.eponae-cv-https.middlewares: compress@file, web-limit@file, eponae-wwwredirect
      traefik.http.routers.eponae-cv-https.tls: true
      traefik.http.routers.eponae-cv-https.tls.certresolver: default
      traefik.http.services.eponae-cv-service.loadbalancer.server.port: '1080'
    environment:
      VIWS_CSP: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'
      VIWS_HEADERS: X-UA-Compatible:ie=edge~content-language:fr
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
      - no-new-privileges