version: '2'

services:
  site:
    image: eponae/cv
    command:
    - -csp
    - default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'
    - -headers
    - X-UA-Compatible:IE-edge
    - -datadogService
    - eponae
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: eponae.fr,www.eponae.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    external_links:
    - monitoring_agent:dd-agent
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik

